/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/backtests/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Backtest */
        post: operations["post_backtest_api_backtests_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Compare */
        get: operations["get_compare_api_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Options */
        get: operations["get_options_api_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Overview */
        get: operations["get_overview_api_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reports */
        get: operations["get_reports_api_reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/digest/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Digest Download */
        get: operations["get_digest_download_api_reports_digest_download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/digest/featured": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Digest Featured */
        get: operations["get_digest_featured_api_reports_digest_featured_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Report */
        post: operations["generate_report_api_reports_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{report_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report Download */
        get: operations["get_report_download_api_reports__report_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Runs */
        get: operations["get_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Runs Queue */
        get: operations["get_runs_queue_api_runs_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Detail */
        get: operations["get_run_detail_api_runs__run_id__detail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Run Favorite */
        post: operations["post_run_favorite_api_runs__run_id__favorite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/universe/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Alerts */
        get: operations["get_alerts_api_universe_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/universe/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Refresh */
        post: operations["post_refresh_api_universe_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/universe/refresh-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Refresh Status */
        get: operations["get_refresh_status_api_universe_refresh_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/universe/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sources */
        get: operations["get_sources_api_universe_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/universe/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Timeline */
        get: operations["get_timeline_api_universe_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Aum */
        Aum: {
            /** Current */
            current: number;
            /** Deltapct */
            deltaPct: number;
            /** Sparkline */
            sparkline: number[];
        };
        /** BacktestAllocation */
        BacktestAllocation: {
            /** Positionpct */
            positionPct: number;
            /** Slots */
            slots: number;
        };
        /** BacktestConfig */
        BacktestConfig: {
            allocation: components["schemas"]["BacktestAllocation"];
            costs: components["schemas"]["BacktestCosts"];
            /** Preset */
            preset: string;
            universe: components["schemas"]["BacktestUniverse"];
            window: components["schemas"]["BacktestWindow"];
        };
        /** BacktestCosts */
        BacktestCosts: {
            /** Feebps */
            feeBps: number;
            /** Slippagebps */
            slippageBps: number;
        };
        /** BacktestUniverse */
        BacktestUniverse: {
            /** Excludestable */
            excludeStable: boolean;
            /** Excludewrapped */
            excludeWrapped: boolean;
            /** Topn */
            topN: number;
        };
        /** BacktestWindow */
        BacktestWindow: {
            /**
             * End
             * Format: date
             */
            end: string;
            /**
             * Rebalance
             * @enum {string}
             */
            rebalance: "Weekly" | "Biweekly" | "Monthly";
            /**
             * Start
             * Format: date
             */
            start: string;
        };
        /** ChampionSummary */
        ChampionSummary: {
            /** Annualized Turnover */
            annualized_turnover: number;
            /** Btc Stop Confirm Days */
            btc_stop_confirm_days?: number | null;
            /** Btc Stop Lookback Days */
            btc_stop_lookback_days?: number | null;
            /** Cagr */
            cagr: number;
            /** Display Name */
            display_name: string;
            /** Ending Equity */
            ending_equity: number;
            /** Initial Asset */
            initial_asset?: string | null;
            /** Leader Pool */
            leader_pool?: string | null;
            /** Max Drawdown */
            max_drawdown: number;
            /** Min Daily Dollar Volume */
            min_daily_dollar_volume?: number | null;
            /** Min History Days */
            min_history_days?: number | null;
            /** Monthly Win Rate */
            monthly_win_rate: number;
            /** Multiple */
            multiple: number;
            /** Rebalance Frequency */
            rebalance_frequency?: string | null;
            /** Regime Mode */
            regime_mode?: string | null;
            /** Risk Off Asset */
            risk_off_asset?: string | null;
            /** Sharpe */
            sharpe: number;
            /** Strategy */
            strategy: string;
            /** Total Return */
            total_return?: number | null;
            /** Weight Momentum Rank */
            weight_momentum_rank?: number | null;
            /** Weight Near High Rank */
            weight_near_high_rank?: number | null;
            /** Weight Ret 21 Rank */
            weight_ret_21_rank?: number | null;
            /** Weight Ret 42 Rank */
            weight_ret_42_rank?: number | null;
            /** Window End */
            window_end: string;
            /** Window Start */
            window_start: string;
        };
        /** CompareEquityPoint */
        CompareEquityPoint: {
            /** Ts */
            ts: string;
            /** Values */
            values: {
                [key: string]: number;
            };
        };
        /** CompareMetrics */
        CompareMetrics: {
            /** Avg Turnover */
            avg_turnover: {
                [key: string]: number;
            };
            /** Cagr */
            cagr: {
                [key: string]: number;
            };
            /** Calmar */
            calmar: {
                [key: string]: number;
            };
            /** Max Dd */
            max_dd: {
                [key: string]: number;
            };
            /** Sharpe */
            sharpe: {
                [key: string]: number;
            };
            /** Sortino */
            sortino: {
                [key: string]: number;
            };
            /** Trades Per Year */
            trades_per_year: {
                [key: string]: number;
            };
            /** Win Rate */
            win_rate: {
                [key: string]: number;
            };
        };
        /** CompareOverlap */
        CompareOverlap: {
            /** Matrix */
            matrix: number[][];
            /** Sharedholdings */
            sharedHoldings: components["schemas"]["CompareSharedHolding"][];
            /** Symbols */
            symbols: string[];
        };
        /** ComparePayload */
        ComparePayload: {
            /**
             * Data Source
             * @default real
             * @enum {string}
             */
            data_source: "real" | "fallback";
            /** Equity */
            equity: components["schemas"]["CompareEquityPoint"][];
            metrics: components["schemas"]["CompareMetrics"];
            overlap: components["schemas"]["CompareOverlap"];
            /** Strategies */
            strategies?: components["schemas"]["StrategyOption"][];
        };
        /** CompareSharedHolding */
        CompareSharedHolding: {
            /** Count */
            count: number;
            /** Symbol */
            symbol: string;
            /** Total */
            total: number;
        };
        /** DataAlert */
        DataAlert: {
            /**
             * Icon
             * @enum {string}
             */
            icon: "alert-triangle" | "info" | "check-circle";
            /** Id */
            id: string;
            /** Meta */
            meta: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "rose" | "cyan" | "emerald";
            /** Source */
            source: string;
            /** Title */
            title: string;
            /** Ts */
            ts: string;
        };
        /** DataSource */
        DataSource: {
            /** Id */
            id: string;
            /** Last Sync Seconds */
            last_sync_seconds: number;
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "healthy" | "degraded" | "error";
        };
        /** EquityOverlay */
        EquityOverlay: {
            /** Atlas Label */
            atlas_label: string;
            /** Btc Label */
            btc_label: string;
            /**
             * Range
             * @enum {string}
             */
            range: "1M" | "3M" | "YTD" | "1Y" | "ALL";
            /** Series */
            series: components["schemas"]["EquityOverlayPoint"][];
        };
        /** EquityOverlayPoint */
        EquityOverlayPoint: {
            /** Atlas */
            atlas: number;
            /** Btc */
            btc: number;
            /** Ts */
            ts: string;
        };
        /** FeaturedDigest */
        FeaturedDigest: {
            /**
             * Defaultformat
             * @enum {string}
             */
            defaultFormat: "markdown" | "pdf" | "png" | "csv" | "bundle";
            /** Formats */
            formats: ("markdown" | "pdf" | "png" | "csv" | "bundle")[];
            /** Generated At */
            generated_at: string;
            /** Id */
            id: string;
            /** Subtitle */
            subtitle: string;
            /** Title */
            title: string;
        };
        /** GenerateReportRequest */
        GenerateReportRequest: {
            /** Format */
            format?: ("markdown" | "pdf" | "png" | "csv" | "bundle") | null;
            /** Formats */
            formats?: ("markdown" | "pdf" | "png" | "csv" | "bundle")[];
            /** Notes */
            notes?: string | null;
            /** Run Id */
            run_id?: string | null;
            /** Strategy */
            strategy?: string | null;
            /**
             * Type
             * @default run
             * @enum {string}
             */
            type: "weekly" | "run" | "compare" | "universe";
        };
        /** GenerateReportResponse */
        GenerateReportResponse: {
            /** Files */
            files: components["schemas"]["GeneratedReportFile"][];
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @constant
             */
            status: "completed";
            /** Warnings */
            warnings: string[];
        };
        /** GeneratedReportFile */
        GeneratedReportFile: {
            /** Generated At */
            generated_at: string;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "markdown" | "pdf" | "png" | "csv" | "bundle";
            /** Path */
            path: string;
            /** Run Id */
            run_id?: string | null;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeroKpi */
        HeroKpi: {
            /** Maxdd */
            maxDd: number;
            /** Sharpe */
            sharpe: number;
            /** Winrate */
            winRate: number;
            /** Ytdreturn */
            ytdReturn: number;
        };
        /** OptionsPayload */
        OptionsPayload: {
            /** Feebpsrange */
            feeBpsRange: number[];
            /** Presets */
            presets: components["schemas"]["PresetOption"][];
            /** Rebalances */
            rebalances: components["schemas"]["OptionsRebalance"][];
            /** Sectors */
            sectors: string[];
            /** Slippagebpsrange */
            slippageBpsRange: number[];
            /** Strategies */
            strategies?: components["schemas"]["StrategyOption"][];
            /** Universes */
            universes: components["schemas"]["OptionsUniverseSize"][];
        };
        /** OptionsRebalance */
        OptionsRebalance: {
            /** Label */
            label: string;
            /**
             * Value
             * @enum {string}
             */
            value: "Weekly" | "Biweekly" | "Monthly";
        };
        /** OptionsUniverseSize */
        OptionsUniverseSize: {
            /** Label */
            label: string;
            /** Topn */
            topN: number;
        };
        /** OverviewPayload */
        OverviewPayload: {
            aum: components["schemas"]["Aum"];
            champion: components["schemas"]["ChampionSummary"];
            /** Daily Returns */
            daily_returns: components["schemas"]["SeriesPoint"][];
            /**
             * Data Source
             * @default real
             * @enum {string}
             */
            data_source: "real" | "fallback";
            /** Equity Curve */
            equity_curve: components["schemas"]["SeriesPoint"][];
            equity_overlay: components["schemas"]["EquityOverlay"];
            hero_kpi: components["schemas"]["HeroKpi"];
            /** Last Sync Seconds */
            last_sync_seconds: number;
            rebalance: components["schemas"]["RebalanceInfo"];
            regime: components["schemas"]["RegimeInfo"];
            /** Selection History */
            selection_history: components["schemas"]["SelectionHistoryRow"][];
            strategies: components["schemas"]["StrategiesBreakdown"];
            /** Top Strategies */
            top_strategies: components["schemas"]["StrategySummary"][];
        };
        /** PresetOption */
        PresetOption: {
            /** Display Name */
            display_name: string;
            /** Slug */
            slug: string;
        };
        /** RebalanceInfo */
        RebalanceInfo: {
            /** Swaps */
            swaps: components["schemas"]["RebalanceSwap"][];
            /** Ts */
            ts: string;
        };
        /** RebalanceSwap */
        RebalanceSwap: {
            /** Deltapct */
            deltaPct: number;
            /** In */
            in: string;
            /** Out */
            out: string;
        };
        /** RegimeInfo */
        RegimeInfo: {
            /**
             * Label
             * @enum {string}
             */
            label: "RISK-ON" | "NEUTRAL" | "RISK-OFF";
            /** Model */
            model: string;
            /** Score */
            score: number;
        };
        /** ReportEntry */
        ReportEntry: {
            /** Generated At */
            generated_at: string;
            /** Highlight */
            highlight?: boolean | null;
            /** Id */
            id: string;
            /**
             * Report Type
             * @enum {string}
             */
            report_type: "weekly" | "run" | "compare" | "universe";
            /** Size Bytes */
            size_bytes: number;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "generating";
            /** Subtitle */
            subtitle: string;
            /**
             * Thumbnail
             * @enum {string}
             */
            thumbnail: "equity" | "lines" | "heatmap" | "bars" | "horizontal-bars" | "sparkbar";
            /** Title */
            title: string;
        };
        /** RunDetailEquityOverlay */
        RunDetailEquityOverlay: {
            /** Series */
            series: components["schemas"]["EquityOverlayPoint"][];
        };
        /** RunDetailPayload */
        RunDetailPayload: {
            /** Created At */
            created_at: string;
            /** Drawdown Series */
            drawdown_series?: components["schemas"]["RunDetailSeriesPoint"][];
            /** Duration S */
            duration_s?: number | null;
            equity_overlay: components["schemas"]["RunDetailEquityOverlay"];
            /** Eta S */
            eta_s?: number | null;
            /** Favorited */
            favorited?: boolean | null;
            kpi: components["schemas"]["RunKpi"];
            /** Max Dd */
            max_dd?: number | null;
            /** Return Pct */
            return_pct?: number | null;
            /** Return Series */
            return_series?: components["schemas"]["RunDetailSeriesPoint"][];
            /** Run Id */
            run_id: string;
            /** Selected Strategy */
            selected_strategy?: string | null;
            /** Sharpe */
            sharpe?: number | null;
            /** Spark */
            spark?: number[] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "completed" | "failed" | "cancelled";
            /** Strategy */
            strategy: string;
            /** Strategy Family */
            strategy_family?: ("ATLAS" | "Momentum" | "MeanRev" | "Carry" | "Other") | null;
            /** Trade Rows */
            trade_rows?: components["schemas"]["RunTradeRow"][];
            /** Turnover Rows */
            turnover_rows?: components["schemas"]["RunTurnoverRow"][];
            /** Universe */
            universe: string;
            window: components["schemas"]["RunWindow"];
        };
        /** RunDetailSeriesPoint */
        RunDetailSeriesPoint: {
            /** Atlas */
            atlas: number;
            /** Btc */
            btc: number;
            /** Ts */
            ts: string;
        };
        /** RunKpi */
        RunKpi: {
            /** Cagr */
            cagr: number;
            /** Calmar */
            calmar: number;
            /** Max Dd */
            max_dd: number;
            /** Sharpe */
            sharpe: number;
            /** Sortino */
            sortino: number;
            /** Win Rate */
            win_rate: number;
        };
        /** RunRow */
        RunRow: {
            /** Created At */
            created_at: string;
            /** Duration S */
            duration_s?: number | null;
            /** Eta S */
            eta_s?: number | null;
            /** Favorited */
            favorited?: boolean | null;
            /** Max Dd */
            max_dd?: number | null;
            /** Return Pct */
            return_pct?: number | null;
            /** Run Id */
            run_id: string;
            /** Selected Strategy */
            selected_strategy?: string | null;
            /** Sharpe */
            sharpe?: number | null;
            /** Spark */
            spark?: number[] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "completed" | "failed" | "cancelled";
            /** Strategy */
            strategy: string;
            /** Strategy Family */
            strategy_family?: ("ATLAS" | "Momentum" | "MeanRev" | "Carry" | "Other") | null;
            /** Universe */
            universe: string;
            window: components["schemas"]["RunWindow"];
        };
        /** RunRowSummary */
        RunRowSummary: {
            /** Duration S */
            duration_s?: number | null;
            /** Eta S */
            eta_s?: number | null;
            /** Favorited */
            favorited?: boolean | null;
            /** Params Summary */
            params_summary: string;
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "completed" | "failed" | "cancelled";
            /** Strategy */
            strategy: string;
        };
        /** RunTradeRow */
        RunTradeRow: {
            /** Coin Id */
            coin_id: string;
            /** Coin Rank */
            coin_rank?: number | null;
            /** Coin Score */
            coin_score?: number | null;
            /** Coin Weight */
            coin_weight?: number | null;
            /** Rebalance Date */
            rebalance_date: string;
            /** Strategy */
            strategy?: string | null;
        };
        /** RunTurnoverRow */
        RunTurnoverRow: {
            /** Annualized Turnover */
            annualized_turnover?: number | null;
            /** Average Holdings */
            average_holdings?: number | null;
            /** Avg Turnover Per Rebalance */
            avg_turnover_per_rebalance?: number | null;
            /** Strategy */
            strategy: string;
        };
        /** RunWindow */
        RunWindow: {
            /** End */
            end: string;
            /** Start */
            start: string;
        };
        /** RunsListResponse */
        RunsListResponse: {
            /** Items */
            items: components["schemas"]["RunRow"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Total */
            total: number;
        };
        /** SelectionHistoryRow */
        SelectionHistoryRow: {
            /** Coin Id */
            coin_id: string;
            /** Coin Rank */
            coin_rank: number;
            /** Coin Score */
            coin_score?: number | null;
            /** Coin Weight */
            coin_weight: number;
            /** Rebalance Date */
            rebalance_date: string;
        };
        /** SeriesPoint */
        SeriesPoint: {
            /** Date */
            date: string;
            /** Value */
            value: number;
        };
        /** StrategiesBreakdown */
        StrategiesBreakdown: {
            /** Breakdown */
            breakdown: components["schemas"]["StrategyBreakdownItem"][];
            /** Total */
            total: number;
        };
        /** StrategyBreakdownItem */
        StrategyBreakdownItem: {
            /** Count */
            count: number;
            /** Family */
            family: string;
        };
        /** StrategyOption */
        StrategyOption: {
            /** Display Name */
            display_name: string;
            /** Strategy */
            strategy: string;
        };
        /** StrategySummary */
        StrategySummary: {
            /** Annualized Turnover */
            annualized_turnover?: number | null;
            /** Cagr */
            cagr: number;
            /** Max Drawdown */
            max_drawdown: number;
            /** Monthly Win Rate */
            monthly_win_rate?: number | null;
            /** Multiple */
            multiple: number;
            /** Sharpe */
            sharpe: number;
            /** Strategy */
            strategy: string;
        };
        /** UniverseRange */
        UniverseRange: {
            /** End */
            end: string;
            /** Start */
            start: string;
        };
        /** UniverseRotation */
        UniverseRotation: {
            /** Label */
            label: string;
            /** Ts */
            ts: string;
        };
        /** UniverseTimelinePayload */
        UniverseTimelinePayload: {
            /**
             * Data Source
             * @default real
             * @enum {string}
             */
            data_source: "real" | "fallback";
            range: components["schemas"]["UniverseRange"];
            /** Rotations */
            rotations: components["schemas"]["UniverseRotation"][];
            /** Segments */
            segments: components["schemas"]["UniverseTimelineSegment"][];
            /** Tokens */
            tokens: string[];
        };
        /** UniverseTimelineSegment */
        UniverseTimelineSegment: {
            /** End */
            end: string;
            /** Start */
            start: string;
            /** Token */
            token: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_backtest_api_backtests_run_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                "X-API-Key"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRowSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_compare_api_compare_get: {
        parameters: {
            query?: {
                ids?: string;
                range?: "1M" | "3M" | "YTD" | "1Y" | "ALL";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparePayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_options_api_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptionsPayload"];
                };
            };
        };
    };
    get_overview_api_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewPayload"];
                };
            };
        };
    };
    get_reports_api_reports_get: {
        parameters: {
            query?: {
                sort?: "recent" | "oldest" | "size" | "type";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_digest_download_api_reports_digest_download_get: {
        parameters: {
            query?: {
                format?: "markdown" | "pdf" | "png" | "csv" | "bundle";
            };
            header?: {
                "X-API-Key"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_digest_featured_api_reports_digest_featured_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeaturedDigest"];
                };
            };
        };
    };
    generate_report_api_reports_generate_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_download_api_reports__report_id__download_get: {
        parameters: {
            query?: {
                format?: ("markdown" | "pdf" | "png" | "csv" | "bundle") | null;
            };
            header?: {
                "X-API-Key"?: string | null;
                Authorization?: string | null;
            };
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_runs_api_runs_get: {
        parameters: {
            query?: {
                q?: string;
                chips?: string;
                dateRange?: "7d" | "30d" | "90d" | "ytd" | "all";
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_runs_queue_api_runs_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRowSummary"][];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                Authorization?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_detail_api_runs__run_id__detail_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_run_favorite_api_runs__run_id__favorite_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                Authorization?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alerts_api_universe_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataAlert"][];
                };
            };
        };
    };
    post_refresh_api_universe_refresh_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_refresh_status_api_universe_refresh_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | null;
                    };
                };
            };
        };
    };
    get_sources_api_universe_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataSource"][];
                };
            };
        };
    };
    get_timeline_api_universe_timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseTimelinePayload"];
                };
            };
        };
    };
}
